apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hugo-blog-hpa
  namespace: blog
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hugo-blog
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80