apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: git@github.com:daisukebtw/blog-k8s.git
    targetRevision: HEAD
    path: prod

  destination:
    server: https://kubernetes.default.svc
    namespace: blog

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
